feat: adding query method to paq
savq/paq-nvim pull request #165
Opened 2024-02-04 10:03 UTC by saccarosium

Related to: #164 

This little new method let's query paq's registry of packages to let the user have custom functionality like notify if the are packages to install at startup.

### Example

Notify user when there are new packages to install.

```lua
vim.api.nvim_create_autocmd("VimEnter", {
	once = true,
	callback = function() 
            local pkgs_count = #require("paq").query("to_install")
            if pkgs_count < 1 then return end
	        print(string.format("There are %d to install", pkgs_count))
	end
})
```

You can even setup automatic packages installation at startup.

```lua
vim.api.nvim_create_autocmd("VimEnter", {
	once = true,
	callback = function() 
        local pkgs_count = #require("paq").query("to_install")
        if pkgs_count < 1 then return end
		require("paq").install()
	end
})
```

2024-02-11 04:10 UTC, savq commented on doc/paq-nvim.txt
> +  fileters by passing one of the following strings:
```suggestion
Queries paq's packages storage with predicate function passed directly to
  |vim.tbl_filter|. Also it lets the user use one of the already defined
  filters by passing one of the following strings:
```

2024-02-11 04:54 UTC, savq requested changes
It makes sense to open up some of this functionality, but I'm still not sure we should allow the user to pass arbitrary functions because 
* The user would have to know the structure of `Package`, and
* we'd be committing to preserving the structure of the `Package` "type", which currently isn't public.

Allowing the built-in filters is probably enough for now...

2024-02-11 14:13 UTC, saccarosium commented
I've made the changes. 

I think we might also revamp the docs to provide a cookbook with some o the ways you could use paq to achieve some of the behaviors that other package managers has. But in another commit.

2024-02-12 02:38 UTC, savq approved these changes

2024-02-12 03:00 UTC, merged

2024-02-12 03:46 UTC, savq commented
> I think we might also revamp the docs to provide a cookbook with some o the ways you could use paq to achieve some of the behaviors that other package managers has. But in another commit.

Yeah, there's a little bit of that in the misc section of the docs. We can add more info there.

There's never too much documentation 🤓